/**
 * OrgLimitEvent model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  OrgLimitEvent,
  OrgLimitEventWithRelations,
  OrgLimitEventSelect,
  OrgLimitEventFilter,
  OrgLimitEventOrderBy,
  CreateOrgLimitEventInput,
  UpdateOrgLimitEventInput,
  OrgLimitEventPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class OrgLimitEventModel {
  constructor(private client: OrmClient) {}
  findMany<S extends OrgLimitEventSelect>(
    args: FindManyArgs<S, OrgLimitEventFilter, OrgLimitEventOrderBy> & {
      select: S;
    } & StrictSelect<S, OrgLimitEventSelect>
  ): QueryBuilder<{
    orgLimitEvents: ConnectionResult<InferSelectResult<OrgLimitEventWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgLimitEvent',
      'orgLimitEvents',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgLimitEventFilter',
      'OrgLimitEventOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgLimitEvent',
      fieldName: 'orgLimitEvents',
      document,
      variables,
    });
  }
  findFirst<S extends OrgLimitEventSelect>(
    args: FindFirstArgs<S, OrgLimitEventFilter> & {
      select: S;
    } & StrictSelect<S, OrgLimitEventSelect>
  ): QueryBuilder<{
    orgLimitEvents: {
      nodes: InferSelectResult<OrgLimitEventWithRelations, S>[];
    };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgLimitEvent',
      'orgLimitEvents',
      args.select,
      {
        where: args?.where,
      },
      'OrgLimitEventFilter',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgLimitEvent',
      fieldName: 'orgLimitEvents',
      document,
      variables,
    });
  }
  create<S extends OrgLimitEventSelect>(
    args: CreateArgs<S, CreateOrgLimitEventInput['orgLimitEvent']> & {
      select: S;
    } & StrictSelect<S, OrgLimitEventSelect>
  ): QueryBuilder<{
    createOrgLimitEvent: {
      orgLimitEvent: InferSelectResult<OrgLimitEventWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgLimitEvent',
      'createOrgLimitEvent',
      'orgLimitEvent',
      args.select,
      args.data,
      'CreateOrgLimitEventInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgLimitEvent',
      fieldName: 'createOrgLimitEvent',
      document,
      variables,
    });
  }
}
