/**
 * Entity-aware config row for the identity_providers_module, which provisions a per-database
     identity_providers table holding OAuth2 / OIDC (and future SAML) provider definitions.
     The scope column determines which config_secrets_module table the rotate proc targets
     (app_secrets for app scope, org_secrets for org scope). When scope = platform,
     the secrets table gets a database_id column and platform-level RLS via
     AuthzRelatedEntityMembership through database.owner_id.
     Scoping matrix:
       scope=app       → per-database flat, in-app admin manages
       scope=platform  → per-database, platform admin manages (generate:constructive)
       scope=org       → per-org tenant, org admin manages
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { identityProvidersModuleKeys } from '../query-keys';
import type {
  IdentityProvidersModuleSelect,
  IdentityProvidersModuleWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  IdentityProvidersModuleSelect,
  IdentityProvidersModuleWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const identityProvidersModuleQueryKey = identityProvidersModuleKeys.detail;
/**
 * Entity-aware config row for the identity_providers_module, which provisions a per-database
     identity_providers table holding OAuth2 / OIDC (and future SAML) provider definitions.
     The scope column determines which config_secrets_module table the rotate proc targets
     (app_secrets for app scope, org_secrets for org scope). When scope = platform,
     the secrets table gets a database_id column and platform-level RLS via
     AuthzRelatedEntityMembership through database.owner_id.
     Scoping matrix:
       scope=app       → per-database flat, in-app admin manages
       scope=platform  → per-database, platform admin manages (generate:constructive)
       scope=org       → per-org tenant, org admin manages
 * 
 * @example
 * ```tsx
 * const { data, isLoading } = useIdentityProvidersModuleQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useIdentityProvidersModuleQuery<
  S extends IdentityProvidersModuleSelect,
  TData = {
    identityProvidersModule: InferSelectResult<IdentityProvidersModuleWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, IdentityProvidersModuleSelect>;
  } & Omit<
    UseQueryOptions<
      {
        identityProvidersModule: InferSelectResult<IdentityProvidersModuleWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useIdentityProvidersModuleQuery(
  params: {
    id: string;
    selection: SelectionConfig<IdentityProvidersModuleSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<IdentityProvidersModuleSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: identityProvidersModuleKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .identityProvidersModule.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Entity-aware config row for the identity_providers_module, which provisions a per-database
     identity_providers table holding OAuth2 / OIDC (and future SAML) provider definitions.
     The scope column determines which config_secrets_module table the rotate proc targets
     (app_secrets for app scope, org_secrets for org scope). When scope = platform,
     the secrets table gets a database_id column and platform-level RLS via
     AuthzRelatedEntityMembership through database.owner_id.
     Scoping matrix:
       scope=app       → per-database flat, in-app admin manages
       scope=platform  → per-database, platform admin manages (generate:constructive)
       scope=org       → per-org tenant, org admin manages
 * 
 * @example
 * ```ts
 * const data = await fetchIdentityProvidersModuleQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchIdentityProvidersModuleQuery<
  S extends IdentityProvidersModuleSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, IdentityProvidersModuleSelect>;
}): Promise<{
  identityProvidersModule: InferSelectResult<IdentityProvidersModuleWithRelations, S> | null;
}>;
export async function fetchIdentityProvidersModuleQuery(params: {
  id: string;
  selection: SelectionConfig<IdentityProvidersModuleSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<IdentityProvidersModuleSelect>(params.selection);
  return getClient()
    .identityProvidersModule.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Entity-aware config row for the identity_providers_module, which provisions a per-database
     identity_providers table holding OAuth2 / OIDC (and future SAML) provider definitions.
     The scope column determines which config_secrets_module table the rotate proc targets
     (app_secrets for app scope, org_secrets for org scope). When scope = platform,
     the secrets table gets a database_id column and platform-level RLS via
     AuthzRelatedEntityMembership through database.owner_id.
     Scoping matrix:
       scope=app       → per-database flat, in-app admin manages
       scope=platform  → per-database, platform admin manages (generate:constructive)
       scope=org       → per-org tenant, org admin manages
 * 
 * @example
 * ```ts
 * await prefetchIdentityProvidersModuleQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchIdentityProvidersModuleQuery<S extends IdentityProvidersModuleSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, IdentityProvidersModuleSelect>;
  }
): Promise<void>;
export async function prefetchIdentityProvidersModuleQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<IdentityProvidersModuleSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<IdentityProvidersModuleSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: identityProvidersModuleKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .identityProvidersModule.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
