/**
 * ORM Client - createClient factory
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from './client';
import type { OrmClientConfig } from './client';
import { AgentPlanModel } from './models/agentPlan';
import { AgentModel } from './models/agent';
import { AgentThreadModel } from './models/agentThread';
import { AgentMessageModel } from './models/agentMessage';
import { AgentTaskModel } from './models/agentTask';
import { AgentPromptModel } from './models/agentPrompt';
import { AgentResourceChunkModel } from './models/agentResourceChunk';
import { AgentPersonaModel } from './models/agentPersona';
import { AgentResourceModel } from './models/agentResource';
import { createMutationOperations } from './mutation';
export type { OrmClientConfig, QueryResult, GraphQLError, GraphQLAdapter } from './client';
export { GraphQLRequestError, FetchAdapter } from './client';
export { QueryBuilder } from './query-builder';
export * from './select-types';
export * from './models';
export { createMutationOperations } from './mutation';
/**
 * Create an ORM client instance
 *
 * @example
 * ```typescript
 * const db = createClient({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer token' },
 * });
 *
 * // Query users
 * const users = await db.user.findMany({
 *   select: { id: true, name: true },
 *   first: 10,
 * }).execute();
 *
 * // Create a user
 * const newUser = await db.user.create({
 *   data: { name: 'John', email: 'john@example.com' },
 *   select: { id: true },
 * }).execute();
 * ```
 */
export function createClient(config: OrmClientConfig) {
  const client = new OrmClient(config);
  return {
    agentPlan: new AgentPlanModel(client),
    agent: new AgentModel(client),
    agentThread: new AgentThreadModel(client),
    agentMessage: new AgentMessageModel(client),
    agentTask: new AgentTaskModel(client),
    agentPrompt: new AgentPromptModel(client),
    agentResourceChunk: new AgentResourceChunkModel(client),
    agentPersona: new AgentPersonaModel(client),
    agentResource: new AgentResourceModel(client),
    mutation: createMutationOperations(client),
  };
}
